Agrego un main simple
algoritmos-rw/algo2_taller_git pull request #1
Opened 2020-06-05 18:31 UTC by fedebrasburg

Agrego un main simple con la función sumar

2020-06-05 21:54 UTC, tutecano1995 requested changes
Buen trabajo @fedebrasburg! Te dejo algunos comentarios para que revises, cualquier duda preguntame.

2020-06-05 21:54 UTC, tutecano1995 commented on main.c
> +  printf("El resultado fue %i", resultado);
Creo que falta agregar `#include <stdio.h>` para que funcione el `printf`

2020-06-05 21:54 UTC, tutecano1995 commented on main.c
> +  printf("El resultado fue %i", resultado);
```suggestion
  printf("El resultado fue %i\n", resultado);
```

2020-06-05 21:54 UTC, tutecano1995 commented on main.c
> +}
Por qué no hacemos una librería aparte para todas las funciones matemáticas?

2020-06-05 21:54 UTC, tutecano1995 commented on main.c
> +  int resultado = sumar(1 , 4);
Creo que estaría bueno eliminar el espacio que le sigue al `1`

2020-06-10 23:20 UTC, fedebrasburg commented on main.c
> +}
Dale, me parece buena idea, podemos hacerlo cuando tengamos alguna función mas

2020-06-10 23:27 UTC, tutecano1995 approved these changes
Buen trabajo Fede! Por mi está bien así 🏄  🌊

2020-06-10 23:53 UTC, merged